### ISSUE TITLE
Unstable Generator Training

### ISSUE THREAD

**Issue by paulhager** [Haoyulance/SC-GAN#3]
Hi,

This implementation looks very good, but I'm having a bit of trouble getting the generator to train on an ADNI dataset for PET prediction. I had to turn attn off because of memory constraints on my GPU, but after around 8 epochs the generators loss spikes into the thousands and then quickly both models stop learning. What would you recommend I play around with to try and stabilize the training? The loss weights?

**Comment by Haoyulance** [comment]
Hi Paul, 

In this case, I think you can try to turn on '--reg' parameters and change '--g_reg' and '--d_reg' accordingly to control the regularization weights. I also recommend checking tensorboard regularly.

**Comment by paulhager** [comment]
Was data quality issues as usual...
