### ISSUE TITLE
RMSE Calc Question

### ISSUE THREAD

**Issue by paulhager** [Haoyulance/SC-GAN#4]
Hi,

On line 97 of your training.py script, why do you divide by 2 at the end? I understand dividing by three because you're adding up the means of your three slice planes, but where does the 2 come from? Also, couldn't you just calculate 

`np.sqrt(np.mean(np.square(masked_output-masked_output)))`

or even better 

`np.sqrt(np.mean(np.square(temp_pet[mask]-output[mask])))`

**Comment by Haoyulance** [comment]
The evaluation metric we used in the experiment was normalized rmse and dividing 2 is just a part of the definition: NRMSE = rmse/(y_max - y_min). 

We noticed calculating the mean nrmse of three planes for 2D slices is easier to get rid of the background voxels compared to calculating the nrmse for 3D image directly.

**Comment by paulhager** [comment]
Ah ok, I was looking at NRMSE definitions using the mean or standard deviation but now I saw some with min-max. Makes sense!
